// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4pgN7qqKiRmmexMD4CORtsahK7h0Wrk',
    appId: '1:999014746798:web:8b81ff9b141e7abe33bb3f',
    messagingSenderId: '999014746798',
    projectId: 'busbuuk-app',
    authDomain: 'busbuuk-app.firebaseapp.com',
    storageBucket: 'busbuuk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgvEOrVslhjvYH5t8CQunmEEDv4Q6kGU',
    appId: '1:999014746798:android:b2202b6057e42a2133bb3f',
    messagingSenderId: '999014746798',
    projectId: 'busbuuk-app',
    storageBucket: 'busbuuk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMPq5F6mNdZsZTeMxUBQezm_vvKKCnAQ',
    appId: '1:999014746798:ios:a4dcd22b839be22733bb3f',
    messagingSenderId: '999014746798',
    projectId: 'busbuuk-app',
    storageBucket: 'busbuuk-app.firebasestorage.app',
    iosBundleId: 'com.example.busbuuk',
  );
}
